{
 "title": "Alerts",
 "description": "Dashboard to visualize only Open(LIVE) Alerts of AlertManager instead of looking in Slack, Teams, and Emails.",
 "tags": [
  "alertmanager",
  "alert",
  "alerts"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "severity", "label": "Severity", "query": { "query": "ALERTS" } },
   {
    "name": "alertgroup",
    "label": "Group",
    "query": {
     "query": "ALERTS{severity=~\"$severity\"}"
    }
   },
   {
    "name": "alertname",
    "label": "Alert",
    "query": {
     "query": "ALERTS{severity=~\"$severity\",alertgroup=~\"$alertgroup\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "🚨 Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "COUNT(ALERTS{alertstate=\"firing\",alertname=~\"$alertname\",severity!=\"none\"})"
    }
   ]
  },
  {
   "title": "🔥 Total Critical",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "COUNT(ALERTS{alertstate=\"firing\",severity=\"critical\",alertname=~\"$alertname\"})"
    }
   ]
  },
  {
   "title": "⚠️ Total Warning",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "COUNT(ALERTS{alertstate=\"firing\",severity=\"warning\",alertname=~\"$alertname\"})"
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "severity=~\"$severity\"",
     "filters": "severity=~\"$severity\",alertname=~\"$alertname\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "table"
    }
   ]
  },
  {
   "title": "Last Seen Alerts",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lifetime(ALERTS{severity=~\"$severity\",alertstate=\"firing\",alertname=~\"$alertname\"}[$__range])"
    }
   ]
  }
 ]
}