global:
  scrape_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets:
           - alertmanager:9093
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090","localhost:9100"]
  - job_name: "postgres"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9187"]
